[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "Cargo subcommand to manage mono repository"
edition = "2018"
license = "Apache-2.0/MIT"
name = "cargo-mono"
repository = "https://github.com/kdy1/cargo-mono.git"
version = "0.1.2"

[dependencies]
anyhow = "1"
cargo_metadata = "0.11.1"
crates_io_api = "0.6.1"
futures-util = "0.3.5"
petgraph = "0.5.1"
semver = "0.10"
serde = {version = "1", features = ["derive"]}
structopt = "0.3"
tokio = {version = "0.2", features = ["rt-core", "process", "macros", "blocking", "time"]}
toml_edit = "0.2.0"
