[package]
name = "cargo-mono"
description = "Cargo subcommand to manage mono repository"
version = "0.0.0"
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
license = "Apache-2.0/MIT"
repository = "https://github.com/kdy1/cargo-mono.git"
edition = "2018"


[dependencies]
clap = "2.33.1"
cargo_metadata = "0.11.1"
semver = "0.10"